In [3]:
import numpy as np
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [13]:
my_array[:, 2]

array([ 3, 12, 47])

In [75]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [30]:
result = 0
print(np.shape(big_secret))
print(big_secret)
for num in big_secret[:, 50]:
    result+= num
round(result, 2)

(5, 51)
[[1.40000000e+01 1.00000000e+01 6.00000000e+00 5.60000000e+01
  4.00000000e+01 2.40000000e+01 9.80000000e+01 7.00000000e+01
  4.20000000e+01 1.40000000e+02 1.00000000e+02 6.00000000e+01
  1.82000000e+02 1.30000000e+02 7.80000000e+01 2.24000000e+02
  1.60000000e+02 9.60000000e+01 2.66000000e+02 1.90000000e+02
  1.14000000e+02 3.08000000e+02 2.20000000e+02 1.32000000e+02
  3.50000000e+02 2.50000000e+02 1.50000000e+02 3.92000000e+02
  2.80000000e+02 1.68000000e+02 4.34000000e+02 3.10000000e+02
  1.86000000e+02 4.76000000e+02 3.40000000e+02 2.04000000e+02
  5.18000000e+02 3.70000000e+02 2.22000000e+02 5.60000000e+02
  4.00000000e+02 2.40000000e+02 6.02000000e+02 4.30000000e+02
  2.58000000e+02 6.44000000e+02 4.60000000e+02 2.76000000e+02
  6.86000000e+02 4.90000000e+02 2.94000000e+02]
 [3.16227766e+01 3.16543836e+01 3.16859590e+01 3.17175031e+01
  3.17490157e+01 3.17804972e+01 3.18119474e+01 3.18433667e+01
  3.18747549e+01 3.19061123e+01 3.19374388e+01 3.19687347e+01
  3.20000000e+

3154.33

In [40]:
result = 0
for num in big_secret[:, 50]:
    result+= num
result_arr=big_secret[:, :5]
result = result_arr[0][0]+result_arr[1][1]+result_arr[2][2]+result_arr[3][3]+result_arr[4][4]
print(result_arr)
round(result, 2)

[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]


121.37

In [77]:
result = 1
result_arr=big_secret[:, 46:]
for i in range(5):
    #print(i)
    result*=result_arr[i][i]
#result = result_arr[0][0]+result_arr[1][1]+result_arr[2][2]+result_arr[3][3]+result_arr[4][4]
#print(result_arr)
print("result")
print(result)
result2 = result_arr[0][0]*result_arr[1][1]*result_arr[2][2]*result_arr[3][3]*result_arr[4][4]
print("result2")
print(result2)

result
341505315559.2347
result2
341505315559.2347


In [74]:
result = 1
print(np.shape(big_secret))
for row in range(5):
    for col in range(51):
        value = big_secret[row][col]
        if (row%2==0) and (col%2==0):
            #print("Row:",row,"Col:",col,"Val:-1")
            big_secret[row][col] = -1
        elif (row%2!=0) and (col%2!=0):
            big_secret[row][col] = 1
            #print("Row:",row,"Col:",col,"Val:1")
        else:
            big_secret[row][col] = value
            
print(np.shape(big_secret))
result_arr=big_secret[:, 46:]
for i in range(5):
    result*=result_arr[i][i]
    
print(result_arr)
print("Result:")
print(result)


(5, 51)
(5, 51)
[[-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.20900000e+03 -1.00000000e+00  2.40100000e+03
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]]
Result:
-1.0


In [90]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [80]:
np.shape(great_secret)

(100, 3)

In [87]:
result = round(np.cos(great_secret[0]).sum(), 2)
result


0.16

In [88]:
result = great_secret[great_secret>50].sum()
result


5470.0

In [91]:
result = great_secret.flatten()
result[150]

7.0710678118654755

In [96]:
new_arr = np.sort(great_secret, axis = 0)
print(np.shape(new_arr))
print(new_arr[99].sum())

(100, 3)
115.12148016521353
