In [2]:
import numpy as np
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [3]:
my_array[:, 2]

array([ 3, 12, 47])

In [4]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [5]:
result = 0
print(np.shape(big_secret))
print(big_secret)
for num in big_secret[:, 50]:
    result+= num
round(result, 2)

(5, 51)
[[1.40000000e+01 1.00000000e+01 6.00000000e+00 5.60000000e+01
  4.00000000e+01 2.40000000e+01 9.80000000e+01 7.00000000e+01
  4.20000000e+01 1.40000000e+02 1.00000000e+02 6.00000000e+01
  1.82000000e+02 1.30000000e+02 7.80000000e+01 2.24000000e+02
  1.60000000e+02 9.60000000e+01 2.66000000e+02 1.90000000e+02
  1.14000000e+02 3.08000000e+02 2.20000000e+02 1.32000000e+02
  3.50000000e+02 2.50000000e+02 1.50000000e+02 3.92000000e+02
  2.80000000e+02 1.68000000e+02 4.34000000e+02 3.10000000e+02
  1.86000000e+02 4.76000000e+02 3.40000000e+02 2.04000000e+02
  5.18000000e+02 3.70000000e+02 2.22000000e+02 5.60000000e+02
  4.00000000e+02 2.40000000e+02 6.02000000e+02 4.30000000e+02
  2.58000000e+02 6.44000000e+02 4.60000000e+02 2.76000000e+02
  6.86000000e+02 4.90000000e+02 2.94000000e+02]
 [3.16227766e+01 3.16543836e+01 3.16859590e+01 3.17175031e+01
  3.17490157e+01 3.17804972e+01 3.18119474e+01 3.18433667e+01
  3.18747549e+01 3.19061123e+01 3.19374388e+01 3.19687347e+01
  3.20000000e+

3154.33

In [6]:
result = 0
for num in big_secret[:, 50]:
    result+= num
result_arr=big_secret[:, :5]
result = result_arr[0][0]+result_arr[1][1]+result_arr[2][2]+result_arr[3][3]+result_arr[4][4]
print(result_arr)
round(result, 2)

[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]


121.37

In [7]:
result = 1
result_arr=big_secret[:, 46:]
for i in range(5):
    #print(i)
    result*=result_arr[i][i]
#result = result_arr[0][0]+result_arr[1][1]+result_arr[2][2]+result_arr[3][3]+result_arr[4][4]
#print(result_arr)
print("result")
print(result)
result2 = result_arr[0][0]*result_arr[1][1]*result_arr[2][2]*result_arr[3][3]*result_arr[4][4]
print("result2")
print(result2)

result
341505315559.2347
result2
341505315559.2347


In [8]:
result = 1
print(np.shape(big_secret))
for row in range(5):
    for col in range(51):
        value = big_secret[row][col]
        if (row%2==0) and (col%2==0):
            #print("Row:",row,"Col:",col,"Val:-1")
            big_secret[row][col] = -1
        elif (row%2!=0) and (col%2!=0):
            big_secret[row][col] = 1
            #print("Row:",row,"Col:",col,"Val:1")
        else:
            big_secret[row][col] = value
            
print(np.shape(big_secret))
result_arr=big_secret[:, 46:]
for i in range(5):
    result*=result_arr[i][i]
    
print(result_arr)
print("Result:")
print(result)


(5, 51)
(5, 51)
[[-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.20900000e+03 -1.00000000e+00  2.40100000e+03
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]]
Result:
-1.0


In [9]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [10]:
np.shape(great_secret)

(100, 3)

In [11]:
result = round(np.cos(great_secret[0]).sum(), 2)
result


0.16

In [12]:
result = great_secret[great_secret>50].sum()
result


5470.0

In [13]:
result = great_secret.flatten()
result[150]

7.0710678118654755

In [14]:
new_arr = np.sort(great_secret, axis = 0)
print(np.shape(new_arr))
print(new_arr[99].sum())

(100, 3)
115.12148016521353


In [15]:
import pandas as pd
import numpy as np
students_pd = pd.read_csv('~/Git/skillfactory/Unit2/datasheet/students.csv')
students = students_pd.values
print(students)

[[  1.  135.   34.    4. ]
 [  2.  160.   43.    5. ]
 [  3.  163.   40.    4.3]
 [  4.  147.   44.    5. ]
 [  5.  138.   41.    4.7]
 [  6.  149.   54.    3.9]
 [  7.  136.   39.    4.2]
 [  8.  154.   48.    4.9]
 [  9.  137.   35.    3.7]
 [ 10.  165.   60.    4.6]]


In [16]:
mean = np.mean(students[:,-1])
print(mean)

4.430000000000001


In [17]:
median = np.median(students[:,-1])
print(median)

4.449999999999999


In [18]:
#Difference of Students Average to Median Mass rounded to 1 sign
print(round((np.average(students[:,-2])-np.median(students[:,-2])), 1))

1.8


In [19]:
#Correlation between Length and Mass
corr = np.corrcoef(students[:, 1], students[:, 2])
print(corr)

[[1.         0.64314431]
 [0.64314431 1.        ]]


In [20]:
#Correlation between Length and Mass
corr_lm = np.corrcoef(students[:, 1], students[:, 2])
print(corr_lm[0])

#Correlation between Length and Avg
corr_la = np.corrcoef(students[:, 1], students[:, 3])
print(corr_la[0])

#Correlation between Mass and Avg
corr_ma = np.corrcoef(students[:, 2], students[:, 3])
print(corr_ma[0])

[1.         0.64314431]
[1.         0.46293714]
[1.         0.29801325]


In [21]:
#Standart Deviation in Length
std = np.std(students[:, 1])
print(std)

11.083320801997928


In [22]:
#Standart Deviation in Avg
std = np.std(students[:, -1])
print(std)

0.4517742799230607


In [23]:
#Dispersion in Mass
std = np.std(students[:, 2])
avg = np.average(students[:, 2])
print(std**2)

60.36


In [24]:
new_array = np.ones((4,4,4,4))
print(np.shape(new_array))
print(new_array)

new_array = np.ones((4,4))
print(np.shape(new_array))
print(new_array)


(4, 4, 4, 4)
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

 

In [25]:
np.full((10, 5), 1) #Module 9.7 - Task 2 - whats wrong??

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
print(np.shape(my_array))
print(my_array[1:4, 1:4])

(5, 5)
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [27]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
print(np.shape(my_sin))
print(my_sin)
print(round(np.sum(my_sin), 3))

(5, 5)
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]
-0.058


In [28]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
print(np.shape(my_sin))
print(my_sin)
print(round(np.sum(my_sin), 3))
my_sin[1:4,1:4] = 1
print(round(np.sum(my_sin), 3))

(5, 5)
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]
-0.058
7.572


In [29]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
print(np.shape(my_sin))
print(my_sin)
print(round(np.sum(my_sin), 3))
my_sin[1:4,1:4] = 1
print(round(np.sum(my_sin), 3))


(5, 5)
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]
-0.058
7.572


In [56]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)

my_sin[1:4,1:4] = 1
print("array 1")
print(np.shape(my_sin))
print(my_sin)
new_my_sin = my_sin[:,0:4].flatten()
print("array new")
print(np.shape(new_my_sin))
print(new_my_sin)
new_reshaped_my_sin = new_my_sin.reshape((10,2))
print("array reshaped")
print(np.shape(new_reshaped_my_sin))
print(new_reshaped_my_sin)
print(round(np.sum(new_reshaped_my_sin[:,0]), 3))

array 1
(5, 5)
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   1.          1.          1.         -0.54402111]
 [-0.99999021  1.          1.          1.          0.65028784]
 [-0.28790332  1.          1.          1.          0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]]
array new
(20,)
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.2794155   1.
  1.          1.         -0.99999021  1.          1.          1.
 -0.28790332  1.          1.          1.          0.83665564 -0.00885131
 -0.8462204  -0.90557836]
array reshaped
(10, 2)
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.2794155   1.        ]
 [ 1.          1.        ]
 [-0.99999021  1.        ]
 [ 1.          1.        ]
 [-0.28790332  1.        ]
 [ 1.          1.        ]
 [ 0.83665564 -0.00885131]
 [-0.8462204  -0.90557836]]
2.406


In [73]:
import numpy as np
data = [x**2 for x in range(101, 1000, 2)]
bigdata = np.array(data)

np.median(bigdata)
print(np.median(bigdata))
print(round(np.std(bigdata),0))
test = bigdata.reshape((225,2))
corr_coef=np.corrcoef(test[:, 0], test[:, 1])
print(corr_coef)

302501.0
292095.0
[[1.         0.99999973]
 [0.99999973 1.        ]]


In [74]:
np.full((10, 5), 1)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])